name: Markdown

on:
  # Run on all pushes and on all pull requests.
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Permissions should be configured at the job level.
permissions: {}

jobs:
  markdownlint:
    permissions:
      contents: read # To clone the repo.

    name: 'Lint Markdown'
    uses: ./.github/workflows/reusable-markdownlint.yml

  remark:
    permissions:
      contents: read # To clone the repo.

    name: 'QA Markdown'
    uses: ./.github/workflows/reusable-remark.yml
