name: Yamllint

on:
  workflow_call:
    inputs:
      strict:
        description: 'Whether to enable strict mode for yamllint.'
        type: boolean
        required: false
        default: false

jobs:
  yamllint:
    name: 'Lint Yaml'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Check for existence of a Yamllint config file
        id: has_config
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
        with:
          files: ".yamllint.y*ml"

      - name: Run Yamllint on all yaml files in repo
        if: ${{ steps.has_config.outputs.files_exists == 'true' }}
        run: yamllint . --format colored ${{ inputs.strict && '--strict' || '' }}

      - name: Pipe Yamllint results on to GH for inline display
        if: ${{ failure() && github.event_name == 'pull_request' }}
        run: yamllint . --format github ${{ inputs.strict && '--strict' || '' }}

  actionlint:
    name: 'Check GHA workflows'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Add problem matcher
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          curl -o actionlint-matcher.json https://raw.githubusercontent.com/rhysd/actionlint/main/.github/actionlint-matcher.json
          echo "::add-matcher::actionlint-matcher.json"

      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
