name: Markdownlint

on:
  workflow_call:

jobs:
  markdownlint:
    name: 'Lint Markdown'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Check for existence of a Markdownlint config file
        id: has_config
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
        with:
          files: ".markdownlint-cli2.y*ml"

      # @link https://github.com/marketplace/actions/problem-matcher-for-markdownlint-cli
      - name: Enable showing issue in PRs
        if: ${{ steps.has_config.outputs.files_exists == 'true' }}
        uses: xt0rted/markdownlint-problem-matcher@1a5fabfb577370cfdf5af944d418e4be3ea06f27 # v3.0.0

      # @link https://github.com/marketplace/actions/markdownlint-cli2-action
      - name: Check markdown with CLI2
        if: ${{ steps.has_config.outputs.files_exists == 'true' }}
        uses: DavidAnson/markdownlint-cli2-action@ce4853d43830c74c1753b39f3cf40f71c2031eb9 # v23.0.0
