name: Yamllint

on:
  # Run on all pushes and on all pull requests.
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  yamllint:
    uses: ./.github/workflows/reusable-yamllint.yml
    with:
      strict: true
